interface TailwindBorderStyleWidthColor {
  borderStyle: string[]
  borderWidth: string[]
  borderColor: string[]
}

const tailwindBorderStyleWidthPlusColor: TailwindBorderStyleWidthColor = {
  borderStyle: [
    'none',
    'pbx-border-solid',
    'pbx-border-dashed',
    'pbx-border-dotted',
    'pbx-border-double',
    'pbx-border-hidden',
  ],
  borderWidth: [
    'none',
    'pbx-border', // 1px
    'pbx-border-2', // 2px
    'pbx-border-4', // 4px
    'pbx-border-8', // 8px
  ],
  borderColor: [
    'none',
    'pbx-border-white',
    'pbx-border-black',

    'pbx-border-slate-50',
    'pbx-border-slate-100',
    'pbx-border-slate-200',
    'pbx-border-slate-300',
    'pbx-border-slate-400',
    'pbx-border-slate-500',
    'pbx-border-slate-600',
    'pbx-border-slate-700',
    'pbx-border-slate-800',
    'pbx-border-slate-900',

    'pbx-border-gray-50',
    'pbx-border-gray-100',
    'pbx-border-gray-200',
    'pbx-border-gray-300',
    'pbx-border-gray-400',
    'pbx-border-gray-500',
    'pbx-border-gray-600',
    'pbx-border-gray-700',
    'pbx-border-gray-800',
    'pbx-border-gray-900',

    'pbx-border-zinc-50',
    'pbx-border-zinc-100',
    'pbx-border-zinc-200',
    'pbx-border-zinc-300',
    'pbx-border-zinc-400',
    'pbx-border-zinc-500',
    'pbx-border-zinc-600',
    'pbx-border-zinc-700',
    'pbx-border-zinc-800',
    'pbx-border-zinc-900',

    'pbx-border-neutral-50',
    'pbx-border-neutral-100',
    'pbx-border-neutral-200',
    'pbx-border-neutral-300',
    'pbx-border-neutral-400',
    'pbx-border-neutral-500',
    'pbx-border-neutral-600',
    'pbx-border-neutral-700',
    'pbx-border-neutral-800',
    'pbx-border-neutral-900',

    'pbx-border-stone-50',
    'pbx-border-stone-100',
    'pbx-border-stone-200',
    'pbx-border-stone-300',
    'pbx-border-stone-400',
    'pbx-border-stone-500',
    'pbx-border-stone-600',
    'pbx-border-stone-700',
    'pbx-border-stone-800',
    'pbx-border-stone-900',

    'pbx-border-red-50',
    'pbx-border-red-100',
    'pbx-border-red-200',
    'pbx-border-red-300',
    'pbx-border-red-400',
    'pbx-border-red-500',
    'pbx-border-red-600',
    'pbx-border-red-700',
    'pbx-border-red-800',
    'pbx-border-red-900',

    'pbx-border-orange-50',
    'pbx-border-orange-100',
    'pbx-border-orange-200',
    'pbx-border-orange-300',
    'pbx-border-orange-400',
    'pbx-border-orange-500',
    'pbx-border-orange-600',
    'pbx-border-orange-700',
    'pbx-border-orange-800',
    'pbx-border-orange-900',

    'pbx-border-amber-50',
    'pbx-border-amber-100',
    'pbx-border-amber-200',
    'pbx-border-amber-300',
    'pbx-border-amber-400',
    'pbx-border-amber-500',
    'pbx-border-amber-600',
    'pbx-border-amber-700',
    'pbx-border-amber-800',
    'pbx-border-amber-900',

    'pbx-border-yellow-50',
    'pbx-border-yellow-100',
    'pbx-border-yellow-200',
    'pbx-border-yellow-300',
    'pbx-border-yellow-400',
    'pbx-border-yellow-500',
    'pbx-border-yellow-600',
    'pbx-border-yellow-700',
    'pbx-border-yellow-800',
    'pbx-border-yellow-900',

    'pbx-border-lime-50',
    'pbx-border-lime-100',
    'pbx-border-lime-200',
    'pbx-border-lime-300',
    'pbx-border-lime-400',
    'pbx-border-lime-500',
    'pbx-border-lime-600',
    'pbx-border-lime-700',
    'pbx-border-lime-800',
    'pbx-border-lime-900',

    'pbx-border-green-50',
    'pbx-border-green-100',
    'pbx-border-green-200',
    'pbx-border-green-300',
    'pbx-border-green-400',
    'pbx-border-green-500',
    'pbx-border-green-600',
    'pbx-border-green-700',
    'pbx-border-green-800',
    'pbx-border-green-900',

    'pbx-border-emerald-50',
    'pbx-border-emerald-100',
    'pbx-border-emerald-200',
    'pbx-border-emerald-300',
    'pbx-border-emerald-400',
    'pbx-border-emerald-500',
    'pbx-border-emerald-600',
    'pbx-border-emerald-700',
    'pbx-border-emerald-800',
    'pbx-border-emerald-900',

    'pbx-border-teal-50',
    'pbx-border-teal-100',
    'pbx-border-teal-200',
    'pbx-border-teal-300',
    'pbx-border-teal-400',
    'pbx-border-teal-500',
    'pbx-border-teal-600',
    'pbx-border-teal-700',
    'pbx-border-teal-800',
    'pbx-border-teal-900',

    'pbx-border-cyan-50',
    'pbx-border-cyan-100',
    'pbx-border-cyan-200',
    'pbx-border-cyan-300',
    'pbx-border-cyan-400',
    'pbx-border-cyan-500',
    'pbx-border-cyan-600',
    'pbx-border-cyan-700',
    'pbx-border-cyan-800',
    'pbx-border-cyan-900',

    'pbx-border-sky-50',
    'pbx-border-sky-100',
    'pbx-border-sky-200',
    'pbx-border-sky-300',
    'pbx-border-sky-400',
    'pbx-border-sky-500',
    'pbx-border-sky-600',
    'pbx-border-sky-700',
    'pbx-border-sky-800',
    'pbx-border-sky-900',

    'pbx-border-blue-50',
    'pbx-border-blue-100',
    'pbx-border-blue-200',
    'pbx-border-blue-300',
    'pbx-border-blue-400',
    'pbx-border-blue-500',
    'pbx-border-blue-600',
    'pbx-border-blue-700',
    'pbx-border-blue-800',
    'pbx-border-blue-900',

    'pbx-border-indigo-50',
    'pbx-border-indigo-100',
    'pbx-border-indigo-200',
    'pbx-border-indigo-300',
    'pbx-border-indigo-400',
    'pbx-border-indigo-500',
    'pbx-border-indigo-600',
    'pbx-border-indigo-700',
    'pbx-border-indigo-800',
    'pbx-border-indigo-900',

    'pbx-border-violet-50',
    'pbx-border-violet-100',
    'pbx-border-violet-200',
    'pbx-border-violet-300',
    'pbx-border-violet-400',
    'pbx-border-violet-500',
    'pbx-border-violet-600',
    'pbx-border-violet-700',
    'pbx-border-violet-800',
    'pbx-border-violet-900',

    'pbx-border-purple-50',
    'pbx-border-purple-100',
    'pbx-border-purple-200',
    'pbx-border-purple-300',
    'pbx-border-purple-400',
    'pbx-border-purple-500',
    'pbx-border-purple-600',
    'pbx-border-purple-700',
    'pbx-border-purple-800',
    'pbx-border-purple-900',

    'pbx-border-fuchsia-50',
    'pbx-border-fuchsia-100',
    'pbx-border-fuchsia-200',
    'pbx-border-fuchsia-300',
    'pbx-border-fuchsia-400',
    'pbx-border-fuchsia-500',
    'pbx-border-fuchsia-600',
    'pbx-border-fuchsia-700',
    'pbx-border-fuchsia-800',
    'pbx-border-fuchsia-900',

    'pbx-border-pink-50',
    'pbx-border-pink-100',
    'pbx-border-pink-200',
    'pbx-border-pink-300',
    'pbx-border-pink-400',
    'pbx-border-pink-500',
    'pbx-border-pink-600',
    'pbx-border-pink-700',
    'pbx-border-pink-800',
    'pbx-border-pink-900',

    'pbx-border-rose-50',
    'pbx-border-rose-100',
    'pbx-border-rose-200',
    'pbx-border-rose-300',
    'pbx-border-rose-400',
    'pbx-border-rose-500',
    'pbx-border-rose-600',
    'pbx-border-rose-700',
    'pbx-border-rose-800',
    'pbx-border-rose-900',
  ],
}

export default tailwindBorderStyleWidthPlusColor
